- hosts: dbservers
  tasks:
        - name: Copy Initial Datafile
          ansible.builtin.copy:
                src: ./data.sql
                dest: /tmp/data.sql
                # owner: ansible
                # group: ansible
                mode: '0644'
