- hosts: dbservers
  become: yes
  tasks:
        - name: Create a new database with name 'online_data'
          community.mysql.mysql_db:
                name: online_data
                state: present
