# The handler is called when the config file is copy'd on to target machine.
# Once complete, apache is restarted.
- name: Install Apache
  hosts: webservers

  handlers: 
    - name: restart apache
      service: 
        name: apache2
        state: restarted

  tasks: 
    - name: Install Apache
      package:
        name: apache2
        state: present

    - name: Copy config
      copy: 
        src: files/test.conf
        dest: /etc/apache2/sites-enabled    
      notify: restart apache
