# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0

# ansible-playbook -i inventory/localhost hello-world-root.yml -K
- hosts: all
  become: yes
  become_method: sudo

  tasks:
  - name: Hello World!
    debug:
      msg: "Hello World!"
