- hosts: webservers
  vars:
      data_dir: /home/ansible/data

  tasks:
  - name: Copy data file
    ansible.builtin.copy:
          src: ./data1.txt
          dest: '{{ data_dir }}'
          # owner: ansible
          # group: ansible
          mode: '0644'
